package agent

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

type opencodeAdapter struct{}

func (opencodeAdapter) Name() string { return "opencode" }

func (opencodeAdapter) Detect(home string) bool {
	if _, err := os.Stat(opencodeConfigDir(home)); err == nil {
		return true
	}
	_, err := exec.LookPath("opencode")
	return err == nil
}

func (opencodeAdapter) Setup(home string) (string, error) {
	return setupOpencode(home)
}

// opencodeConfigDir returns the opencode config directory, respecting XDG_CONFIG_HOME.
func opencodeConfigDir(home string) string {
	if xdg := os.Getenv("XDG_CONFIG_HOME"); xdg != "" {
		return filepath.Join(xdg, "opencode")
	}
	return filepath.Join(home, ".config", "opencode")
}

// opencodePluginTemplate is the JS plugin written to <configDir>/plugins/forge.js.
// %q is replaced with the forge binary path at setup time.
//
// Spawns the forge hook binary directly via child_process. The previous
// implementation used the `$` shell helper from the OpenCode plugin context,
// but OpenCode does not expose `$` to plugins, which produced "$ is not a
// function" at every event. child_process.spawn is universally available and
// avoids shell-quoting risk on the JSON payload.
const opencodePluginTemplate = "// forge.js — Auto-generated by forge init. Do not edit manually.\n" +
	"const { spawn } = require(\"node:child_process\");\n" +
	"\n" +
	"const FORGE_PATH = %q;\n" +
	"\n" +
	"function fireForgeHook(eventType, payload) {\n" +
	"  try {\n" +
	"    const child = spawn(FORGE_PATH, [\"hook\", \"--source\", \"opencode\", \"--event\", eventType], {\n" +
	"      stdio: [\"pipe\", \"ignore\", \"ignore\"],\n" +
	"      detached: false,\n" +
	"    });\n" +
	"    child.on(\"error\", () => {});\n" +
	"    child.stdin.on(\"error\", () => {});\n" +
	"    child.stdin.end(payload);\n" +
	"  } catch (_) {\n" +
	"    // Best-effort capture — never break the host agent on hook failure.\n" +
	"  }\n" +
	"}\n" +
	"\n" +
	"export const ForgePlugin = async () => {\n" +
	"  return {\n" +
	"    \"tool.execute.after\": async (event) => {\n" +
	"      fireForgeHook(\"PostToolUse\", JSON.stringify(event));\n" +
	"    },\n" +
	"    \"session.updated\": async (event) => {\n" +
	"      if (event?.info?.status !== \"idle\") return;\n" +
	"      fireForgeHook(\"Stop\", JSON.stringify(event));\n" +
	"    },\n" +
	"    \"session.deleted\": async (event) => {\n" +
	"      fireForgeHook(\"SessionEnd\", JSON.stringify(event));\n" +
	"    },\n" +
	"    \"session.created\": async (event) => {\n" +
	"      fireForgeHook(\"UserPromptSubmit\", JSON.stringify(event));\n" +
	"    },\n" +
	"  };\n" +
	"};\n"

func setupOpencode(home string) (string, error) {
	forgePath := ForgePath()
	configDir := opencodeConfigDir(home)

	// Upsert <configDir>/opencode.json with the "mcp" section.
	configPath := filepath.Join(configDir, "opencode.json")
	config := make(map[string]any)
	if data, err := os.ReadFile(configPath); err == nil {
		_ = json.Unmarshal(data, &config)
	}

	mcp, _ := config["mcp"].(map[string]any)
	if mcp == nil {
		mcp = make(map[string]any)
	}
	mcp["forge"] = map[string]any{
		"type":    "local",
		"command": []string{forgePath, "mcp"},
	}
	config["mcp"] = mcp

	data, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		return "", fmt.Errorf("marshal opencode config: %w", err)
	}
	if err := WriteFileConfirm(configPath, data, 0o600); err != nil {
		return "", fmt.Errorf("write opencode config: %w", err)
	}

	// Write JS plugin — always overwrite so forgePath stays current after binary moves.
	pluginDir := filepath.Join(configDir, "plugins")
	if err := os.MkdirAll(pluginDir, 0o700); err != nil {
		return "", fmt.Errorf("create opencode plugins dir: %w", err)
	}
	pluginContent := fmt.Sprintf(opencodePluginTemplate, forgePath)
	pluginPath := filepath.Join(pluginDir, "forge.js")
	if err := WriteFileConfirm(pluginPath, []byte(pluginContent), 0o600); err != nil {
		return "", fmt.Errorf("write opencode plugin: %w", err)
	}

	return pluginPath, nil
}
