package agent

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

type opencodeAdapter struct{}

func (opencodeAdapter) Name() string { return "opencode" }

func (opencodeAdapter) Detect(home string) bool {
	if _, err := os.Stat(opencodeConfigDir(home)); err == nil {
		return true
	}
	_, err := exec.LookPath("opencode")
	return err == nil
}

func (opencodeAdapter) Setup(home string) (string, error) {
	return setupOpencode(home)
}

// opencodeConfigDir returns the opencode config directory, respecting XDG_CONFIG_HOME.
func opencodeConfigDir(home string) string {
	if xdg := os.Getenv("XDG_CONFIG_HOME"); xdg != "" {
		return filepath.Join(xdg, "opencode")
	}
	return filepath.Join(home, ".config", "opencode")
}

// opencodePluginTemplate is the JS plugin written to <configDir>/plugins/forge.js.
// %q is replaced with the forge binary path at setup time.
// \x60 is a backtick literal (Go interpreted strings cannot contain raw backticks).
// %%s becomes literal %s in the output (printf format, not a Go verb).
const opencodePluginTemplate = "// forge.js — Auto-generated by forge init. Do not edit manually.\n" +
	"export const ForgePlugin = async ({ $ }) => {\n" +
	"  const forgePath = %q;\n" +
	"  return {\n" +
	"    \"tool.execute.after\": async (event) => {\n" +
	"      const payload = JSON.stringify(event);\n" +
	"      await $\x60printf '%%s' ${payload} | ${forgePath} hook --source opencode --event PostToolUse\x60.nothrow();\n" +
	"    },\n" +
	"    \"session.updated\": async (event) => {\n" +
	"      if (event?.info?.status !== \"idle\") return;\n" +
	"      const payload = JSON.stringify(event);\n" +
	"      await $\x60printf '%%s' ${payload} | ${forgePath} hook --source opencode --event Stop\x60.nothrow();\n" +
	"    },\n" +
	"    \"session.deleted\": async (event) => {\n" +
	"      const payload = JSON.stringify(event);\n" +
	"      await $\x60printf '%%s' ${payload} | ${forgePath} hook --source opencode --event SessionEnd\x60.nothrow();\n" +
	"    },\n" +
	"    \"session.created\": async (event) => {\n" +
	"      const payload = JSON.stringify(event);\n" +
	"      await $\x60printf '%%s' ${payload} | ${forgePath} hook --source opencode --event UserPromptSubmit\x60.nothrow();\n" +
	"    },\n" +
	"  };\n" +
	"};\n"

func setupOpencode(home string) (string, error) {
	forgePath := ForgePath()
	configDir := opencodeConfigDir(home)

	// Upsert <configDir>/opencode.json with the "mcp" section.
	configPath := filepath.Join(configDir, "opencode.json")
	config := make(map[string]any)
	var existingBytes []byte
	if data, err := os.ReadFile(configPath); err == nil {
		existingBytes = data
		_ = json.Unmarshal(data, &config)
	}

	mcp, _ := config["mcp"].(map[string]any)
	if mcp == nil {
		mcp = make(map[string]any)
	}
	mcp["forge"] = map[string]any{
		"type":    "local",
		"command": []string{forgePath, "mcp"},
	}
	config["mcp"] = mcp

	data, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		return "", fmt.Errorf("marshal opencode config: %w", err)
	}
	if !bytes.Equal(existingBytes, data) {
		if err := os.MkdirAll(configDir, 0o700); err != nil {
			return "", fmt.Errorf("create opencode config dir: %w", err)
		}
		if err := os.WriteFile(configPath, data, 0o600); err != nil {
			return "", fmt.Errorf("write opencode config: %w", err)
		}
	}

	// Write JS plugin — always overwrite so forgePath stays current after binary moves.
	pluginDir := filepath.Join(configDir, "plugins")
	if err := os.MkdirAll(pluginDir, 0o700); err != nil {
		return "", fmt.Errorf("create opencode plugins dir: %w", err)
	}
	pluginContent := fmt.Sprintf(opencodePluginTemplate, forgePath)
	pluginPath := filepath.Join(pluginDir, "forge.js")
	if err := os.WriteFile(pluginPath, []byte(pluginContent), 0o600); err != nil {
		return "", fmt.Errorf("write opencode plugin: %w", err)
	}

	return pluginPath, nil
}
