package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"

	"github.com/forge/forge/internal/db"
)

func TestIntersectStrings(t *testing.T) {
	cases := []struct {
		name string
		a, b []string
		want []string
	}{
		{"empty a", nil, []string{"a"}, nil},
		{"empty b", []string{"a"}, nil, nil},
		{"exact match", []string{"a.go", "b.go"}, []string{"a.go", "b.go"}, []string{"a.go", "b.go"}},
		{"partial match", []string{"a.go"}, []string{"a.go", "b.go"}, []string{"a.go"}},
		{"no overlap", []string{"a.go"}, []string{"b.go"}, nil},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := intersectStrings(tc.a, tc.b)
			if len(got) != len(tc.want) {
				t.Fatalf("intersectStrings(%v,%v) = %v, want %v", tc.a, tc.b, got, tc.want)
			}
			for i := range got {
				if got[i] != tc.want[i] {
					t.Errorf("intersectStrings(%v,%v) = %v, want %v", tc.a, tc.b, got, tc.want)
				}
			}
		})
	}
}

func TestDetectRecentFiles(t *testing.T) {
	tmpDir := t.TempDir()
	initGitRepo(t, tmpDir)

	f := filepath.Join(tmpDir, "recent.go")
	mustWriteFile(t, f, "package main\n")

	out := chdirDo(t, tmpDir, func() []string { return detectRecentFiles() })
	if len(out) == 0 {
		t.Fatal("expected at least 1 file")
	}
	found := false
	for _, f := range out {
		if f == "recent.go" {
			found = true
			break
		}
	}
	if !found {
		t.Fatalf("expected recent.go in %v", out)
	}
}

func TestDetectRecentFilesCleanTree(t *testing.T) {
	tmpDir := t.TempDir()
	initGitRepo(t, tmpDir)

	f := filepath.Join(tmpDir, "clean.go")
	mustWriteFile(t, f, "package main\n")
	git(t, tmpDir, "add", "clean.go")
	git(t, tmpDir, "commit", "-m", "add clean.go")

	mustWriteFile(t, f, "package main\n\nfunc main() {}\n")

	out := chdirDo(t, tmpDir, func() []string { return detectRecentFiles() })
	if len(out) == 0 {
		t.Fatal("expected at least 1 file")
	}
	found := false
	for _, f := range out {
		if f == "clean.go" {
			found = true
			break
		}
	}
	if !found {
		t.Fatalf("expected clean.go in %v", out)
	}
}

func TestGetPushFiles(t *testing.T) {
	tmpDir := t.TempDir()
	initGitRepo(t, tmpDir)

	f := filepath.Join(tmpDir, "push.go")
	mustWriteFile(t, f, "package main\n")
	git(t, tmpDir, "add", "push.go")

	out := chdirDo(t, tmpDir, func() []string { return getPushFiles() })
	if len(out) == 0 {
		t.Fatal("expected at least 1 file")
	}
}

func TestGetPushFilesStaged(t *testing.T) {
	tmpDir := t.TempDir()
	initGitRepo(t, tmpDir)

	f := filepath.Join(tmpDir, "staged.go")
	mustWriteFile(t, f, "package main\n")
	git(t, tmpDir, "add", "staged.go")

	out := chdirDo(t, tmpDir, func() []string { return getPushFiles() })
	found := false
	for _, f := range out {
		if f == "staged.go" {
			found = true
			break
		}
	}
	if !found {
		t.Fatalf("expected staged.go in %v", out)
	}
}

func TestPrePushCheckFindsNoConflict(t *testing.T) {
	tmpDir := t.TempDir()
	initGitRepo(t, tmpDir)
	t.Setenv("HOME", tmpDir)

	database := openTestDB(t, forgeDBPath(tmpDir))
	insertPrinciple(t, database, projectName(t, tmpDir), "unrelated principle", 0.9, []string{"unrelated.go"})
	database.Close()

	f := filepath.Join(tmpDir, "new.go")
	mustWriteFile(t, f, "package main\n")

	code := chdirDo(t, tmpDir, func() int { return runPrePushCheck() })
	if code != 0 {
		t.Errorf("expected exit 0, got %d", code)
	}
}

func TestPrePushCheckBlocksConflict(t *testing.T) {
	tmpDir := t.TempDir()
	initGitRepo(t, tmpDir)
	t.Setenv("HOME", tmpDir)

	database := openTestDB(t, forgeDBPath(tmpDir))
	insertPrinciple(t, database, projectName(t, tmpDir), "do not edit this file", 0.8, []string{"conflict.go"})
	database.Close()

	f := filepath.Join(tmpDir, "conflict.go")
	mustWriteFile(t, f, "package main\n")
	git(t, tmpDir, "add", "conflict.go")

	code := chdirDo(t, tmpDir, func() int { return runPrePushCheck() })
	if code != 1 {
		t.Errorf("expected exit 1, got %d", code)
	}
}

func TestPrePushCheckLowImpact(t *testing.T) {
	tmpDir := t.TempDir()
	initGitRepo(t, tmpDir)
	t.Setenv("HOME", tmpDir)

	database := openTestDB(t, forgeDBPath(tmpDir))
	insertPrinciple(t, database, projectName(t, tmpDir), "low impact thing", 0.3, []string{"low.go"})
	database.Close()

	f := filepath.Join(tmpDir, "low.go")
	mustWriteFile(t, f, "package main\n")
	git(t, tmpDir, "add", "low.go")

	code := chdirDo(t, tmpDir, func() int { return runPrePushCheck() })
	if code != 0 {
		t.Errorf("expected exit 0 for low impact, got %d", code)
	}
}

func TestGetPushFilesUntracked(t *testing.T) {
	tmpDir := t.TempDir()
	initGitRepo(t, tmpDir)

	mustWriteFile(t, filepath.Join(tmpDir, "untracked.go"), "package main\n")

	out := chdirDo(t, tmpDir, func() []string { return getPushFiles() })
	found := false
	for _, f := range out {
		if f == "untracked.go" {
			found = true
			break
		}
	}
	if !found {
		t.Fatalf("expected untracked.go in %v", out)
	}
}

func TestPrePushCheckNoProject(t *testing.T) {
	tmpDir := t.TempDir()
	code := chdirDo(t, tmpDir, func() int { return runPrePushCheck() })
	if code != 0 {
		t.Errorf("expected exit 0 outside git repo, got %d", code)
	}
}

func TestPrePushCheckMultipleFiles(t *testing.T) {
	tmpDir := t.TempDir()
	initGitRepo(t, tmpDir)
	t.Setenv("HOME", tmpDir)

	database := openTestDB(t, forgeDBPath(tmpDir))
	insertPrinciple(t, database, projectName(t, tmpDir), "principle for a.go", 0.8, []string{"a.go"})
	insertPrinciple(t, database, projectName(t, tmpDir), "principle for b.go", 0.9, []string{"b.go"})
	database.Close()

	mustWriteFile(t, filepath.Join(tmpDir, "a.go"), "package a\n")
	mustWriteFile(t, filepath.Join(tmpDir, "b.go"), "package b\n")
	git(t, tmpDir, "add", "a.go", "b.go")

	code := chdirDo(t, tmpDir, func() int { return runPrePushCheck() })
	if code != 1 {
		t.Errorf("expected exit 1 for multiple conflicts, got %d", code)
	}
}

// chdirDo changes to dir, runs fn, restores original dir.
func chdirDo[T any](t *testing.T, dir string, fn func() T) T {
	t.Helper()
	cwd, err := os.Getwd()
	if err != nil {
		t.Fatalf("Getwd: %v", err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatalf("Chdir %s: %v", dir, err)
	}
	defer func() {
		if err := os.Chdir(cwd); err != nil {
			t.Errorf("restore Chdir %s: %v", cwd, err)
		}
	}()
	return fn()
}

func projectName(t *testing.T, tmpDir string) string {
	t.Helper()
	return filepath.Base(tmpDir)
}

func initGitRepo(t *testing.T, dir string) {
	t.Helper()
	git(t, dir, "init", "--initial-branch=main")
	git(t, dir, "config", "user.email", "test@test.com")
	git(t, dir, "config", "user.name", "Test")
	mustWriteFile(t, filepath.Join(dir, "README.md"), "# test\n")
	git(t, dir, "add", "README.md")
	git(t, dir, "commit", "-m", "initial")
}

func git(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %v: %v\n%s", args, err, out)
	}
}

func mustWriteFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func openTestDB(t *testing.T, path string) *db.DB {
	t.Helper()
	database, err := db.Open(path)
	if err != nil {
		t.Fatalf("open DB %s: %v", path, err)
	}
	return database
}

func forgeDBPath(home string) string {
	return filepath.Join(home, ".forge", "forge.db")
}

func insertPrinciple(t *testing.T, database *db.DB, projectID, title string, impact float64, files []string) {
	t.Helper()
	_, err := database.InsertPrinciple(&db.Principle{
		ID:           fmt.Sprintf("%s-%s", projectID, title),
		TS:           time.Now().UTC().Format(time.RFC3339),
		Type:         "pattern",
		Title:        title,
		Narrative:    "Test narrative for: " + title,
		ImpactScore:  impact,
		ProjectID:    projectID,
		FilesModified: files,
	})
	if err != nil {
		t.Fatalf("insert principle %q: %v", title, err)
	}
}
